<a href="https://colab.research.google.com/github/tennille-bernard/Kal-Academy-Assignments/blob/main/Assignment_2_2_TB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part 2:**
In this assignment, you will complete a notebook where you will build a classifier to predict whether a loan case will be paid off or not.  

Assumption: Principal is quoted in thousands so 1000 is actually 1M

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset1 = pd.read_csv('loan_train.csv')
dataset1.head()


Unnamed: 0.1  Unnamed: 0 loan_status  Principal  terms effective_date  \
0             0           0     PAIDOFF       1000     30       9/8/2016   
1             2           2     PAIDOFF       1000     30       9/8/2016   
2             3           3     PAIDOFF       1000     15       9/8/2016   
3             4           4     PAIDOFF       1000     30       9/9/2016   
4             6           6     PAIDOFF       1000     30       9/9/2016   

    due_date  age             education  Gender  
0  10/7/2016   45  High School or Below    male  
1  10/7/2016   33              Bechalor  female  
2  9/22/2016   27               college    male  
3  10/8/2016   28               college  female  
4  10/8/2016   29               college    male

In [ ]:
for col in ['due_date', 'effective_date']:
    dataset1[col] = pd.to_datetime(dataset1[col]).apply(lambda date: date.toordinal())

In [ ]:
X1 = dataset1.iloc[:, 3:].values
y1 = dataset1.iloc[:, 2].values
print(y1[0:5])

['PAIDOFF' 'PAIDOFF' 'PAIDOFF' 'PAIDOFF' 'PAIDOFF']


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5,6])], remainder='passthrough')
X1 = np.array(ct.fit_transform(X1))
print(X1[0:3, :])

[[0.0 1.0 0.0 0.0 0.0 1.0 1000 30 736215 736244 45]
 [1.0 0.0 0.0 0.0 1.0 0.0 1000 30 736215 736244 33]
 [0.0 0.0 0.0 1.0 0.0 1.0 1000 15 736215 736229 27]]


In [ ]:
for i in range(len(y1)):
    if y1[i] == 'PAIDOFF':
        y1[i] = 1
    else:
        y1[i] = 0

y1 = y1.astype(int)
print(np.unique(y1))
print(y1[1])


[0 1]
1


**Splitting the data**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size = 0.2, random_state = 0)

**Scaling the data**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Classification models**  
**K_Nearest Neighbour**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


KNeighborsClassifier()

**Testing Classification Model: KNN**
Remember to convert date

In [ ]:
#Change values for eff_date, due_date
from datetime import datetime # Import the datetime module

eff_date ="09/10/1985"
eff_date = datetime.strptime(eff_date, "%m/%d/%Y").toordinal() # Convert the string to a datetime object first, then get the ordinal

due_date ="09/20/1985"
due_date = datetime.strptime(due_date, "%m/%d/%Y").toordinal() # Convert the string to a datetime object first, then get the ordinal


print(eff_date,",",due_date)

724894 , 724904


In [ ]:
#enter format: education, gender, principal, terms, effective date, due date, age. Use eff_date and due_date values printed above.
#Education format (first four entries): bachelor, college, high school, masters. Add 1 in the respective column, and 0 for the rest.
#Gender format (next 2 entries): female, male. Add 1 in the respective column, 0 for the other.
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([1])

Based on the reading, a college educated female with a $1M ($1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 **would pay off** their house.

**Checking the accuracy score of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 4  8]
 [ 8 50]]


0.7714285714285715

Not bad for a model. True diagonal (TP, TN) > false diagonal (FP, FN), with an accuracy score of 0.77.

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([0])

Based on this model, a college educated female with a  1M( 1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 **would not pay off** their house.

**Checking the accuracy score of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   #prints predicted values of the test data then the actual values of the test d

[[1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 2 10]
 [ 2 56]]


0.8285714285714286

This is a better model. True diagonal (TP, TN) > false diagonal (FP, FN), with an accuracy score of 0.83.

**Model: SVM**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([0])

Based on this model, a college educated female with a 1M( 1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 would not pay off their house.

**Checking the accuracy score of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0 12]
 [ 0 58]]


0.8285714285714286

SVM and Logistic Regression gave the same score.

**Model: Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([1])

Based on this model, a college educated female with a  1M( 1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 **would pay off** their house.

**Checking the accuracy of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   #prints predicted values of the test data then the actual values of the test d

[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 9  3]
 [11 47]]


0.8

This is a good model, but SVM and Logistic Regression were better. True diagonal (TP, TN) > false diagonal (FP, FN), with an accuracy score of 0.8.

**Model: Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([1])

Based on this model, a college educated female with a 1M( 1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 **would pay off** their house.

**Checking the accuracy of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   #prints predicted values of the test data then the actual values of the test d

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  4]
 [14 44]]


0.7428571428571429

This is a good model, but SVM and Logistic Regression were better. True diagonal (TP, TN) > false diagonal (FP, FN), with an accuracy score of 0.74.

**Model: Decision Tree Classification**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
classifier.predict(sc.transform([[0,1,0,0,1,0,1000,30,724894, 724904, 39, ]]))

array([1])

Based on this model, a college educated female with a 1M( 1000 K) principal and a 30 year term, purchasing the house with an effective date of 09/10/1985 and due date of 09/20/1985 **would pay off** their house.

**Checking the accuracy of the model**

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   #prints predicted values of the test data then the actual values of the test d

[[1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  6]
 [10 48]]


0.7714285714285715

This is a good model, but SVM and Logistic Regression were better. True diagonal (TP, TN) > false diagonal (FP, FN), with an accuracy score of 0.74.

**Summary**  

Based on the accuracy scores of the models, the most accurate classification model was: SVM and Logistic Regression. Either of these models would be the one I used going forward.  

Both models state that the prediction is that the woman in question with the given effective and due dates would not be able to pay off her house.